- hosts: raspberrypi
  become: true

  tasks:

    - name: "Install samba packages"
      package:
        name:
          - samba
          - samba-common-bin
        state: present

    - name: "Ensure samba service is enabled and running"
      service:
        name: smbd
        state: started
        enabled: yes

    - name: "Ensure smb.conf exists"
      template:
        src: samba.conf
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify:
        - "Restart Samba"

    # To-Do: need improvement
    # the storage need to be mounted in a location where samba service and pi user
    # can edit the content
    - name: "Enable access to all users to media home"
      file:
        path: "/media/pi"
        owner: pi
        group: pi
        mode: '0777'

    - name: "Ensure hddspindown.sh exists"
      template:
        src: hddspindown.sh
        dest: /sbin/hddspindown.sh
        owner: root
        group: root
        mode: '0755'
        backup: yes

    - name: "Ensure hddspindown.sh exists"
      template:
        src: properpoweroff.service
        dest: /etc/systemd/system/properpoweroff.service
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify:
        - "Systemctl properpoweroff reload"

    - name: "Ensure properpoweroff service is enabled and running"
      service:
        name: properpoweroff
        state: started
        enabled: yes

  handlers:

    - name: "Restart Samba"
      service:
        name: smbd
        state: restarted

    - name: "Systemctl properpoweroff reload"
      shell: systemctl daemon-reload